# Generated by Django 4.1.5 on 2023-01-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0003_dummytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyTest',
        ),
    ]
