# Generated by Django 4.1.5 on 2023-01-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
