# Generated by Django 4.1.5 on 2023-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0007_remove_auditlog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
